// Code generated by entc, DO NOT EDIT.

package profile

import (
	"time"
)

const (
	// Label holds the string label denoting the profile type in the database.
	Label = "profile"
	// FieldID holds the string denoting the id field in the database.
	FieldID        = "id"         // FieldEmail holds the string denoting the email vertex property in the database.
	FieldEmail     = "email"      // FieldRemark holds the string denoting the remark vertex property in the database.
	FieldRemark    = "remark"     // FieldUpdatedAt holds the string denoting the updatedat vertex property in the database.
	FieldUpdatedAt = "updated_at" // FieldCreatedAt holds the string denoting the createdat vertex property in the database.
	FieldCreatedAt = "created_at"

	// EdgeUser holds the string denoting the user edge name in mutations.
	EdgeUser = "user"

	// Table holds the table name of the profile in the database.
	Table = "profiles"
	// UserTable is the table the holds the user relation/edge.
	UserTable = "profiles"
	// UserInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	UserInverseTable = "users"
	// UserColumn is the table column denoting the user relation/edge.
	UserColumn = "user_profile"
)

// Columns holds all SQL columns for profile fields.
var Columns = []string{
	FieldID,
	FieldEmail,
	FieldRemark,
	FieldUpdatedAt,
	FieldCreatedAt,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the Profile type.
var ForeignKeys = []string{
	"user_profile",
}

var (
	// DefaultUpdatedAt holds the default value on creation for the updatedAt field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultCreatedAt holds the default value on update for the createdAt field.
	UpdateDefaultCreatedAt func() time.Time
)
